name: Test Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Test Action
        id: test-action
        uses: darcymccoy/merge-conflict-action@396efe09e919aadfaab2b7ab49777d7053ab288f
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          post-comments: true